#!/bin/bash
# Copyright (c) 2019 Achim D. Brucker
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# SPDX-License-Identifier: BSD-2-Clause

set -e 

if [ -f ../../config ]; then 
   source ../../config
else
   CONFIG=`git rev-parse --show-toplevel`/config
   if [ -f $CONFIG ];
       source $CONFIG
   fi
fi

# Generate Isabelle image
ISA_URL="https://isabelle.in.tum.de/website-Isabelle"$VERSION"/dist/Isabelle"$VERSION"_linux.tar.gz"
if [ "$LATEST" == "$VERSION" ]; then
  AFP_URL="https://www.isa-afp.org/release/"
  AFP_TAR=`curl -s $AFP_URL  | grep "afp-[0-9]" | sed -e 's|^.*href="\(.*\)">.*$|\1|;s|".*$||' | sort -r | head -1`

else
    # URL for determining name of archive:
    AFP_URL="https://sourceforge.net/projects/afp/files/afp-Isabelle$VERSION/"
    AFP_TAR=`curl -L -s $AFP_URL  | grep "afp-[0-9].*[a-z]</span" | sed -e 's|^.*>\(afp-.*\)</s.*$|\1|' | sort -r | head -1`
    # URL for direct download    
    AFP_URL="https://downloads.sourceforge.net/project/afp/afp-Isabelle$VERSION"
fi

for url in $ISA_URL $AFP_URL/$AFP_TAR; do
  if curl --output /dev/null --silent --head --fail "$url"; then
    echo "URL exists: $url"
  else
    echo "URL does not exist: $url"
    exit 1
  fi
done

$CONTAINER build -t logicalhacking/isabelle$VERSION . \
             --build-arg uid="$DOCKERUID" \
             --build-arg sessions="$SESSIONS" \
             --build-arg isabelle="$ISA_URL" \
             --build-arg afp="$AFP_URL/$AFP_TAR"
