pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building Isabelle 2017'
		sh './build.sh 2017 Functional-Automata'
                echo 'Building Isabelle 2018'
		sh './build.sh 2018 Functional-Automata'
            }
        }
    }
}
